---
- name: "Deploy InfluxDB"
  hosts:
    - influxdb
  remote_user: root
  gather_facts: yes

  vars_files:
    - vault.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: openldap
      when:  openldap_server_ip is defined and openldap_server_ip != None
    - import_role:
        name: ceph-fs
      when:
        - shared_storage
        - storage_backend == "cephfs"
    - import_role:
        name: influxdb
      when: "'influxdb' in group_names"
    - import_role:
        name: telegraf
      when: "'telegraf' in group_names"
    - setup:
