---
- name: Deploy InfluxDB
  hosts: influxdb
  become: True
  remote_user: root
  tasks:
    - include_role:
        name: influxdb
      tags:
        - install
        - configure
        - influxdb
        - verify
        - stress
        - demo
        - prometheus
