---
- name: Install any necessary dependencies [Debian/Ubuntu]
  apt:
    name: "{{ influxdb_dependency_pkgs }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install any necessary PIP dependencies [Debian/Ubuntu]
  apt:
    name: "{{ python_pkgs }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: influxdb_install_python_client

- name: Import InfluxData GPG signing key [Debian/Ubuntu]
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Add InfluxData repository [Debian/Ubuntu]
  apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ influxdb_install_version }}
    state: present
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB packages [Debian/Ubuntu] # noqa 403
  apt:
    name: influxdb
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Download InfluxDB package via URL [Debian/Ubuntu]
  get_url:
    url: '{{ influxdb_install_url }}'
    dest: /tmp/influxdb-ansible-download.deb
    mode: '0777'
  when: influxdb_install_url is defined and influxdb_install_url != None

- name: Install downloaded InfluxDB package [Debian/Ubuntu]
  apt:
    deb: /tmp/influxdb-ansible-download.deb
    state: present
  when: influxdb_install_url is defined and influxdb_install_url != None
