---
- name: Install any necessary dependencies [RedHat/CentOS]
  yum:
    name: "{{ influxdb_dependency_pkgs }}"
    state: present

- name: Install any necessary PIP dependencies [RedHat/CentOS]
  yum:
    name: "{{ python_pkgs }}"
    state: present
  when: influxdb_install_python_client

- name: Add InfluxData repository file [RHEL/CentOS]
  template:
    src: etc/yum.repos.d/influxdata.repo.j2
    dest: /etc/yum.repos.d/influxdata.repo
    force: yes
    backup: yes
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB packages [RHEL/CentOS]
  yum:
    name: influxdb
    state: latest
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB from URL [RHEL/CentOS] # noqa 403
  yum:
    name: "{{ influxdb_install_url }}"
    state: present
  when: influxdb_install_url is defined and influxdb_install_url != None

- name: Capture installed InfluxDB version # noqa 301 303
  command: rpm -q influxdb
  register: reg_influxdb_version

- debug: var=reg_influxdb_version.stdout_lines
