---
- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- include_tasks:
    file: install.yml
    apply:
      tags:
        - influxdb
        - install
        - configure
  tags: [influxdb, install, configure]

- include_tasks:
    file: configure.yml
    apply:
      tags:
        - influxdb
        - configure
  tags: [influxdb, configure]

- name: Start the InfluxDB service
  systemd:
    name: influxdb
    state: restarted
    enabled: yes
  register: influxdb_started
  when: influxdb_start_service
  tags: [influxdb, configure]

- name: Verify InfluxDB HTTP service is listening # noqa 503
  wait_for:
    host: "{{ influxdb_bind_hostname | default(\"localhost\", true) }}"
    port: "{{ influxdb_http_port }}"
    delay: 30
  when: influxdb_started.changed and influxdb_start_service
  ignore_errors: yes
  register: influxdb_start_attempt
  tags: [influxdb, configure]

- name: Get InfluxDB journald logs if service does not appear to be up # noqa 305
  shell: journalctl _SYSTEMD_INVOCATION_ID=`systemctl show -p InvocationID --value influxdb.service`
  register: influxdb_journal
  when:
    - influxdb_start_attempt.failed is defined
    - influxdb_start_attempt.failed
  tags: [influxdb, configure]

- name: Ensure InfluxDB started
  fail:
    msg: "{{ influxdb_journal.stdout_lines }}"
  when:
    - influxdb_start_attempt.failed is defined
    - influxdb_start_attempt.failed
  tags: [influxdb, configure]

- include_tasks:
    file: demo.yml
    apply:
      tags:
        - influxdb
        - demo
  tags: [influxdb, demo]
  when: influxdb_load_sample_data and influxdb_http_auth_enabled == "false" and influxdb_start_service

- include_tasks:
    file: verify.yml
    apply:
      tags:
        - influxdb
        - verify
  tags: [influxdb, verify]

- include_tasks:
    file: stress.yml
    apply:
      tags:
        - influxdb
        - stress
  tags: [influxdb, stress]

- include_tasks:
    file: prometheus.yml
    apply:
      tags:
        - prometheus
  tags: [prometheus]
