- name: install prometheus packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - prometheus
    - prometheus-alertmanager
    - prometheus-node-exporter
    - prometheus-pushgateway

- name: Add ceph and unifi exporter configs to prometheus.yml
  blockinfile:
    path: /etc/prometheus/prometheus.yml
    block: |
        - job_name: 'ceph-exporter'
          static_configs:
            - targets: ['localhost:9128']
              labels:
                alias: ceph-exporter
        - job_name: 'unifi-exporter'
          static_configs:
            - targets: ['{{ unifi_admin_host }}:9130']
              labels:
                alias: unifi-exporter
