---
- name: purge metaid
  file:
    path: /var/opt/influxdb/meta/id
    state: absent

- name: purge raftdb
  file:
    path: /var/opt/influxdb/meta/raft.db
    state: absent

- name: purge peers
  file:
    path: /var/opt/influxdb/meta/peers.json
    state: absent

- name: restart influxdb
  service:
    name: influxdb
    state: restarted

- name: pause
  pause:
    seconds: 3

- name: restart unifi_exporter
  systemd:
    name: docker-unifi_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart ceph_exporter
  systemd:
    name: docker-ceph_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
